#!/bin/bash

0. alias ls="rm *"

1. echo "hello $USER"

2. export PATH=$PATH:/action


3. echo $((`echo $PATH | grep -o ":/" | wc -l`+ 1))


4. printenv

5. set

6. BETTY="Holberton"

7. export HOLBERTON="Betty"

8. echo $(($TRUEKNOWLEDGE + 128))

9. echo $(($POWER / $DIVIDE))

10. echo $(($BREATH**$LOVE))

11. echo $((2#$BINARY))

12. echo {a..z}{a..z} | tr " " "\n" | grep -v "oo"

13. printf "%.2f" $NUM | sort

14. printf '%x\n' $DECIMAL

15. tr `echo {a..z} | tr -d ' '` `echo {n..z} $(echo {a..m}) | tr -d ' '` | tr `echo {A..Z} | tr -d ' '` `echo {N..Z} $(echo {A..M}) | tr -d ' '`

16. perl -lne 'print if $. % 2 == 1'

17. echo $(printf %o $(($((5#$(echo $WATER | tr 'water' '01234'))) + $((5#$(echo $STIR | tr 'stir.' '01234'))))) | tr '01234567' 'behlnort')
